baseURL = "/"
languageCode = "en-us"
title = "Spot the Octopus"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
# Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
# googleAnalytics = ""
enableRobotsTXT = true
disable_share = true
disableShare = true
DisableShare = true

[languages]
  [languages.en]
    title = "Spot the Octopus"
    weight = 1
    contentDir = "content"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = "/spot-hugo/favicon.ico"
  # https://github.com/theNewDynamic/gohugo-theme-ananke/tree/8845854aa9ab5af79066e840d8c884fbbb8a269d?tab=readme-ov-file#logo
  site_logo = "favicon.ico"
  description = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 10
  post_content_classes = "avenir"
  disable_share = true
  disableShare = true
  disableGtagForUniversalAnalytics = true
  disable_gtag_for_universal_analytics = true
